defaults: &defaults
  app:
    name: test topline
  api:
    port: 8080
    host: 127.0.0.1
  db:
    connectionLimit: 10
    host: 127.0.0.1
    user: root
    password: '127000'
    database: topline

development:
  <<: *defaults

production:
  <<: *defaults
